[package]
name = "jal-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.4.1"
rand = "0.8.5"
random_word = { version = "0.4.1", features = ["en", "fr"] }
